repos:
  # Basic Hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

  #  Terraform (fmt/validate + optional tflint)
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_fmt
        args: [--args=-recursive] # Recursively checks all files in the directory
        files: ^terraform/ # Only checks terraform files
      - id: terraform_validate # Removes ANSI colors
        args: [--args=-no-color]
        files: ^terraform/
      - id: terraform_tflint
        args: [--args=--disable-rule=terraform_comment_syntax]
        files: ^terraform/

  #  Semgrep (SAST)
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.92.0
    hooks:
      - id: semgrep
        args: [--config, p/ci, --error, --timeout, "120"] # Runs default configuration and blocks commit if failed. timesout after 120s
        pass_filenames: true          # scan only staged files

  #  Gitleaks (secrets)

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        args: [detect, --redact]
        pass_filenames: false         # scan the working tree
        
