name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - uses: terraform-linters/setup-tflint@v4
        with: { tflint_version: latest }

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
